# Passwall 2
src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git
src-git passwall2 https://github.com/xiaorouji/openwrt-passwall2.git

# DDNSTO / LinkEase
src-git linkease_packages https://github.com/linkease/nas-packages.git
src-git linkease_luci https://github.com/linkease/nas-packages-luci.git

# Nikki
src-git nikki https://github.com/nikkinikki-org/OpenWrt-nikki.git